#ifndef refBLAS_HPP
#define refBLAS_HPP

//#include "vecfill.hpp" //fills matrices
#include "mm_ijk.hpp" //does matrix multiply...
#include "mm_jki.hpp" //does matrix multiply another way...
#include "mm_kij.hpp" //does matrix multiply one more way...
#include "mm_jik.hpp" //does matrix multiply even more ways...
#include "mm_ikj.hpp" //does matrix multiply one more way again...
#include "mm_kji.hpp" //final permutation of the matrix multiply...


#endif 